"use client";
import localFont from "next/font/local";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css";
import "../index.scss";
import MainProvider from "./MainProvider";
import NoSsr from "../utils/NoSsr";
import AuthProvider from "./providers/authProvider";
import { Providers } from "./Providers";
import React, { useEffect, useState } from "react";

import Gleap from "gleap";
import { getSession } from "next-auth/react";
import { ToastContainer } from "react-toastify";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export default function RootLayout({ children }) {
  const [session, setSession] = useState(null); // Store session here
  const [gleapInitialized, setGleapInitialized] = useState(false);

  const metadata = {
    title: "Theryo.ai",
    description:
      "Theryo.ai is a digital character generated by Artificial Intelligence (AI) technologies that imitate the behavior and qualities of a real human persona",
  };
  useEffect(() => {
    const apiKey = process.env.NEXT_PUBLIC_GLEAP_API_KEY;

    // Initialize Gleap only once
    if (!gleapInitialized) {
      Gleap.initialize(apiKey);
      Gleap.setDisableInAppNotifications(true); // Disable notifications initially
      setGleapInitialized(true);
    }

    // Fetch session and identify user globally
    const fetchSession = async () => {
      let currentSession = await getSession(); // Fetch session manually
      setSession(currentSession); // Set the session state

      if (currentSession && currentSession?.user) {
        // Identify the logged-in user
        Gleap.identify(currentSession?.user?._id || "userId", {
          name: currentSession?.user?.firstName || "Logged User",
          email: currentSession?.user?.email || "email@domain.com",
        });
        Gleap.setDisableInAppNotifications(true); // Disable notifications for logged-in users
        Gleap.showFeedbackButton(true); // Show the feedback widget
      } else {
        Gleap.identify("userId", {
          name: "Guest User",
        });
        Gleap.setDisableInAppNotifications(true); // Disable notifications for guests
      }
    };

    fetchSession();

    return () => {
      Gleap.clearIdentity(true); // Clear identity on unmount
      Gleap.setDisableInAppNotifications(true);
    };
  }, []); // Run only once on component mount

  // Update document title and meta description on component mount
  useEffect(() => {
    const link = document.createElement("link");
    link.setAttribute("rel", "manifest");
    link.setAttribute("href", "/manifest.json");
    document.head.appendChild(link);
    document.title = metadata.title;
    const metaDescriptionTag = document.querySelector(
      'meta[name="description"]'
    );
    if (metaDescriptionTag) {
      metaDescriptionTag.setAttribute("content", metadata.description);
    } else {
      const newMetaTag = document.createElement("meta");
      newMetaTag.setAttribute("name", "description");
      newMetaTag.setAttribute("content", metadata.description);
      document.head.appendChild(newMetaTag);
    }

    const themeColorTag = document.querySelector('meta[name="theme-color"]');
    if (themeColorTag) {
      themeColorTag.setAttribute("content", metadata.themeColor);
    } else {
      const newThemeColorTag = document.createElement("meta");
      newThemeColorTag.setAttribute("name", "theme-color");
      newThemeColorTag.setAttribute("content", metadata.themeColor);
      document.head.appendChild(newThemeColorTag);
    }

    let viewportTag = document.querySelector('meta[name="viewport"]');
    if (!viewportTag) {
      viewportTag = document.createElement("meta");
      viewportTag.setAttribute("name", "viewport");
      document.head.appendChild(viewportTag);
    }
    viewportTag.setAttribute(
      "content",
      "width=device-width, initial-scale=1.0"
    );
  }, [metadata.title, metadata.description, metadata.themeColor]);

  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Outfit:wght@100..900&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <NoSsr>
          <Providers>
            <AuthProvider>
              <MainProvider>
                {children}
                <ToastContainer
                  position="top-center"
                  autoClose={2000}
                  closeOnClick={true}
                />
              </MainProvider>
            </AuthProvider>
          </Providers>
        </NoSsr>
      </body>
    </html>
  );
}
