"use client";

import {
    Document,
    Page,
    Text,
    StyleSheet,
    View,
    BlobProvider,
    Font,
} from "@react-pdf/renderer";

// register fonts for pdf templates
Font.register({
    family: 'Albert Sans',
    fonts: [
        { src: '/assets/fonts/Albert_Sans/static/AlbertSans-Regular.ttf', fontWeight: 'normal' },
        { src: '/assets/fonts/Albert_Sans/static/AlbertSans-Bold.ttf', fontWeight: 'bold' }
    ]
});

// Main document component
const PdfDocument = ({ parsedData, date }) => {

    // Define reusable styles
    const styles = StyleSheet.create({
        page: {
            flexDirection: "column",
            paddingTop: 40,
            paddingBottom: 90,
            paddingHorizontal: 40,
            fontFamily: "Albert Sans",
        },
        header: {
            position: "absolute",
            top: 0,
            left: 0,
            right: 40,
            height: 50,
        },
        footer: {
            position: "absolute",
            bottom: 20,
            left: 0,
            right: 0,
            height: 70,
            paddingHorizontal: 40,
            justifyContent: "center",
            alignItems: "center",
        },
        content: {
            flexGrow: 1,
            fontSize: 11,
            fontFamily: "Albert Sans",
        },
        section: {
            fontFamily: "Albert Sans",
            fontSize: 19,
            fontWeight: "bold",
            marginTop: 12,
            marginBottom: 12,
            border: 1,
            padding: 6,
            backgroundColor: "#00b2a9",
            color: "white",
        },
        dateSection: {
            fontFamily: "Albert Sans",
            fontSize: 19,
            fontWeight: "bold",
            marginTop: 12,
            marginBottom: 12,
            border: 2,
            padding: 6,
            backgroundColor: "#fead77",
        },
        bulletItem: {
            flexDirection: "column",
            marginBottom: 4,
        },
        bullet: {
            fontSize: 30,
            color: "green",
        },
        bulletText: {
            flexDirection: "row",
            alignItems: "top",
        },
        boldNested: {
            fontWeight: "bold",
        },
        bulletSymbol: {
            fontSize: 11,
            fontWeight: "bold",
        },
        bulletContent: {
            flex: 1,
            marginRight: 4,
        },
        disclaimer: {
            fontSize: 10,
            color: "red",
        },
        generatedBy: {
            fontSize: 10,
            color: "gray",
            marginTop: 12,
            textAlign: "right",
        },
        text: {
            paddingTop: 6,
            paddingBottom: 6,
        },
        bold: {
            fontWeight: 'bold',
        },
        textNested: {
            fontWeight: "normal",
        }
    });

    // Header component
    const Header = () => (
        <View style={styles.header} fixed>
            <Text style={styles.generatedBy}>Generated by TheryoAI</Text>
        </View>
    );

    // Footer component
    const Footer = () => (
        <View style={styles.footer} fixed>
            <Text style={styles.disclaimer}>
                DISCLAIMER: This report was generated using artificial intelligence
                (AI), which may produce errors, inaccuracies, or biases. The information
                provided should not be used as a substitute for professional medical
                advice, diagnosis, treatment, or independent research and analysis.
                Always consult a licensed healthcare provider before making any
                health-related decisions. The content has not been independently
                verified, and Theryo assumes no liability for reliance on this
                AI-generated report. Human review, critical evaluation, and judgment are
                essential when utilizing the information herein. By using this report,
                you acknowledge and agree to these terms.
            </Text>
        </View>
    );

    return (
        <Document>
            <Page size="A4" style={styles.page}>
                <Header />
                <Footer />
                <View style={styles.content}>
                    <Text style={styles?.dateSection}>Care Plan - {new Date(date).toLocaleDateString('en-US')}</Text>
                    {parsedData?.map((item, index) => (
                        <View key={index}>
                            {(
                                item?.type === "bulletOne" || item?.type === "bulletTwo" || item?.type === "bulletThree" || item?.type === "bulletFour"
                            ) ? (
                                <View style={styles.bulletItem}>
                                    <Text style={{ marginLeft: item?.type === "bulletOne" ? 12 : (item?.type === "bulletTwo" ? 32 : (item?.type === "bulletThree" ? 52 : 72)) }}>
                                        <Text style={styles.bulletSymbol}>{"\u2022"}{" "}{" "}</Text>
                                        {item?.content?.map((bulletItem, bulletIndex) => (
                                            <Text key={bulletIndex} style={styles[bulletItem?.type]}>
                                                {bulletItem?.content}{" "}
                                            </Text>
                                        ))}
                                    </Text>
                                </View>
                            ) : item?.type === "nested" ? (
                                <View>
                                    <Text>
                                        {item?.content?.map((nestedItem, nestedIndex) => (
                                            <Text key={nestedIndex} style={styles[nestedItem?.type]}>
                                                {nestedItem?.content}{" "}
                                            </Text>
                                        ))}
                                    </Text>
                                </View>
                            ) : (
                                item?.content ? <Text style={styles[item?.type]}>{item?.content}</Text> : ""
                            )}
                        </View>
                    ))}
                </View>
            </Page>
        </Document>
    )
};

export default PdfDocument;