import { apiSlice } from "../api/apiSlice";

export const adminApi = apiSlice.injectEndpoints({
    endpoints: (builder) => ({
        fetchAllUsers: builder.query({
            query: () => ({
                url: "getAllUsers",
                method: "GET",
                credentials: "include",
            }),
            keepUnusedDataFor: 0,
        }),
        toggleUserApproval: builder.mutation({
            query: (userId) => ({
                url: `users/${userId}/approve`,
                method: "POST",
                credentials: "include",
            }),
        }),
        deleteUser: builder.mutation({
            query: (userId) => ({
                url: `users/${userId}/delete`,
                method: "DELETE",
                credentials: "include",  // Include credentials like cookies
            }),
        }),
    }),
});

// Export the hooks generated by Redux Toolkit
export const {
    useFetchAllUsersQuery,
    useToggleUserApprovalMutation,
    useDeleteUserMutation,  // Export the deleteUser mutation
} = adminApi;
