export const defaultMoods = [
  {
    mood: "Awesome",
    emoji: "😀",
    color: "#4ade80",
  },
  {
    mood: "Fine",
    emoji: "😐",
    color: "#facc15",
  },
  {
    mood: "Not fine",
    emoji: "☹️",
    color: "#fb923c",
  },
  {
    mood: "Very bad",
    emoji: "😭",
    color: "#ef4444",
  },
];
export const ObjectiveDuration = [
  "1 week",
  "2 weeks",
  "3 weeks",
  "1 month",
  "2 months",
  "3 months",
  "4 months",
  "5 months",
  "6 months",
  "7 months",
  "8 months",
  "9 months",
  "10 months",
  "11 months",
  "12 months",
];

export const strategyData = [
  "Cognitive Challenging",
  "Exploration of Coping Patterns",
  "Mindfulness Training",
  "Role-play/Behavioral Rehearsal",
  "Cognitive Refocusing",
  "Exploration of Emotions",
  "Preventative Services",
  "Structured Problem Solving",
  "Cognitive Reframing",
  "Exploration of Relationship Patterns",
  "Psycho-Education",
  "Supportive Reflection",
  "Communication Skills",
  "Guided Imagery",
  "Relaxation/Deep Breathing",
  "Symptom Management",
  "Compliance Issues",
  "Interactive Feedback",
  "Review of Treatment Plan/Progress",
  "Other",
  "DBT",
  "Interpersonal Resolutions",
];

export const modalityData = [
  "Individual Therapy",
  "Group Therapy",
  "Couple Therapy",
  "Family Therapy",
  "Self-Directed",
  "Community Based",
  "Natural Supports",
];

export const frequencyData = [
  "As Needed",
  "Daily",
  "Once per week",
  "Every other week",
  "Once per month",
  "One time",
];

export const statusData = ["Todo", "In Progress", "Done"];

export const homeData = ["ENTRIES", "YOUR TEAM"];

export const TabData = [
  "Info",
  "To-Do",
  "Documents",
  "Report Data",
  "Shared Summaries"
  // "Global Details",
];
export const notesData = [
  "Today Todo's",
  "Research",
  "Prescription",
  "Send Material",
];

//ISO languages 639-1 name
export const languagesData = [
  {
    name: "Abkhazian",
    code: "ab",
  },
  {
    name: "Afar",
    code: "aa",
  },
  {
    name: "Afrikaans",
    code: "af",
  },
  {
    name: "Akan",
    code: "ak",
  },
  {
    name: "Albanian",
    code: "sq",
  },
  {
    name: "Amharic",
    code: "am",
  },
  {
    name: "Arabic",
    code: "ar",
  },
  {
    name: "Aragonese",
    code: "an",
  },
  {
    name: "Armenian",
    code: "hy",
  },
  {
    name: "Assamese",
    code: "as",
  },
  {
    name: "Avaric",
    code: "av",
  },
  {
    name: "Avestan",
    code: "ae",
  },
  {
    name: "Aymara",
    code: "ay",
  },
  {
    name: "Azerbaijani",
    code: "az",
  },
  {
    name: "Bambara",
    code: "bm",
  },
  {
    name: "Bashkir",
    code: "ba",
  },
  {
    name: "Basque",
    code: "eu",
  },
  {
    name: "Belarusian",
    code: "be",
  },
  {
    name: "Bengali",
    code: "bn",
  },
  {
    name: "Bislama",
    code: "bi",
  },
  {
    name: "Bosnian",
    code: "bs",
  },
  {
    name: "Breton",
    code: "br",
  },
  {
    name: "Bulgarian",
    code: "bg",
  },
  {
    name: "Burmese",
    code: "my",
  },
  {
    name: "Catalan, Valencian",
    code: "ca",
  },
  {
    name: "Chamorro",
    code: "ch",
  },
  {
    name: "Chechen",
    code: "ce",
  },
  {
    name: "Chichewa, Chewa, Nyanja",
    code: "ny",
  },
  {
    name: "Chinese",
    code: "zh",
  },
  {
    name: "Old Church Slavonic",
    code: "cu",
  },
  {
    name: "Chuvash",
    code: "cv",
  },
  {
    name: "Cornish",
    code: "kw",
  },
  {
    name: "Corsican",
    code: "co",
  },
  {
    name: "Cree",
    code: "cr",
  },
  {
    name: "Croatian",
    code: "hr",
  },
  {
    name: "Czech",
    code: "cs",
  },
  {
    name: "Danish",
    code: "da",
  },
  {
    name: "Divehi, Dhivehi, Maldivian",
    code: "dv",
  },
  {
    name: "Dutch, Flemish",
    code: "nl",
  },
  {
    name: "Dzongkha",
    code: "dz",
  },
  {
    name: "English",
    code: "en",
  },
  {
    name: "Esperanto",
    code: "eo",
  },
  {
    name: "Estonian",
    code: "et",
  },
  {
    name: "Ewe",
    code: "ee",
  },
  {
    name: "Faroese",
    code: "fo",
  },
  {
    name: "Fijian",
    code: "fj",
  },
  {
    name: "Finnish",
    code: "fi",
  },
  {
    name: "French",
    code: "fr",
  },
  {
    name: "Western Frisian",
    code: "fy",
  },
  {
    name: "Fulah",
    code: "ff",
  },
  {
    name: "Gaelic, Scottish Gaelic",
    code: "gd",
  },
  {
    name: "Galician",
    code: "gl",
  },
  {
    name: "Ganda",
    code: "lg",
  },
  {
    name: "Georgian",
    code: "ka",
  },
  {
    name: "German",
    code: "de",
  },
  {
    name: "Greek, Modern (1453–)",
    code: "el",
  },
  {
    name: "Kalaallisut, Greenlandic",
    code: "kl",
  },
  {
    name: "Guarani",
    code: "gn",
  },
  {
    name: "Gujarati",
    code: "gu",
  },
  {
    name: "Haitian, Haitian Creole",
    code: "ht",
  },
  {
    name: "Hausa",
    code: "ha",
  },
  {
    name: "Hebrew",
    code: "he",
  },
  {
    name: "Herero",
    code: "hz",
  },
  {
    name: "Hindi",
    code: "hi",
  },
  {
    name: "Hiri Motu",
    code: "ho",
  },
  {
    name: "Hungarian",
    code: "hu",
  },
  {
    name: "Icelandic",
    code: "is",
  },
  {
    name: "Ido",
    code: "io",
  },
  {
    name: "Igbo",
    code: "ig",
  },
  {
    name: "Indonesian",
    code: "id",
  },
  {
    name: "Interlingua (International Auxiliary Language Association)",
    code: "ia",
  },
  {
    name: "Interlingue, Occidental",
    code: "ie",
  },
  {
    name: "Inuktitut",
    code: "iu",
  },
  {
    name: "Inupiaq",
    code: "ik",
  },
  {
    name: "Irish",
    code: "ga",
  },
  {
    name: "Italian",
    code: "it",
  },
  {
    name: "Japanese",
    code: "ja",
  },
  {
    name: "Javanese",
    code: "jv",
  },
  {
    name: "Kannada",
    code: "kn",
  },
  {
    name: "Kanuri",
    code: "kr",
  },
  {
    name: "Kashmiri",
    code: "ks",
  },
  {
    name: "Kazakh",
    code: "kk",
  },
  {
    name: "Central Khmer",
    code: "km",
  },
  {
    name: "Kikuyu, Gikuyu",
    code: "ki",
  },
  {
    name: "Kinyarwanda",
    code: "rw",
  },
  {
    name: "Kirghiz, Kyrgyz",
    code: "ky",
  },
  {
    name: "Komi",
    code: "kv",
  },
  {
    name: "Kongo",
    code: "kg",
  },
  {
    name: "Korean",
    code: "ko",
  },
  {
    name: "Kuanyama, Kwanyama",
    code: "kj",
  },
  {
    name: "Kurdish",
    code: "ku",
  },
  {
    name: "Lao",
    code: "lo",
  },
  {
    name: "Latin",
    code: "la",
  },
  {
    name: "Latvian",
    code: "lv",
  },
  {
    name: "Limburgan, Limburger, Limburgish",
    code: "li",
  },
  {
    name: "Lingala",
    code: "ln",
  },
  {
    name: "Lithuanian",
    code: "lt",
  },
  {
    name: "Luba-Katanga",
    code: "lu",
  },
  {
    name: "Luxembourgish, Letzeburgesch",
    code: "lb",
  },
  {
    name: "Macedonian",
    code: "mk",
  },
  {
    name: "Malagasy",
    code: "mg",
  },
  {
    name: "Malay",
    code: "ms",
  },
  {
    name: "Malayalam",
    code: "ml",
  },
  {
    name: "Maltese",
    code: "mt",
  },
  {
    name: "Manx",
    code: "gv",
  },
  {
    name: "Maori",
    code: "mi",
  },
  {
    name: "Marathi",
    code: "mr",
  },
  {
    name: "Marshallese",
    code: "mh",
  },
  {
    name: "Mongolian",
    code: "mn",
  },
  {
    name: "Nauru",
    code: "na",
  },
  {
    name: "Navajo, Navaho",
    code: "nv",
  },
  {
    name: "North Ndebele",
    code: "nd",
  },
  {
    name: "South Ndebele",
    code: "nr",
  },
  {
    name: "Ndonga",
    code: "ng",
  },
  {
    name: "Nepali",
    code: "ne",
  },
  {
    name: "Norwegian",
    code: "no",
  },
  {
    name: "Norwegian Bokmål",
    code: "nb",
  },
  {
    name: "Norwegian Nynorsk",
    code: "nn",
  },
  {
    name: "Sichuan Yi, Nuosu",
    code: "ii",
  },
  {
    name: "Occitan",
    code: "oc",
  },
  {
    name: "Ojibwa",
    code: "oj",
  },
  {
    name: "Oriya",
    code: "or",
  },
  {
    name: "Oromo",
    code: "om",
  },
  {
    name: "Ossetian, Ossetic",
    code: "os",
  },
  {
    name: "Pali",
    code: "pi",
  },
  {
    name: "Pashto, Pushto",
    code: "ps",
  },
  {
    name: "Persian",
    code: "fa",
  },
  {
    name: "Polish",
    code: "pl",
  },
  {
    name: "Portuguese",
    code: "pt",
  },
  {
    name: "Punjabi, Panjabi",
    code: "pa",
  },
  {
    name: "Quechua",
    code: "qu",
  },
  {
    name: "Romanian, Moldavian, Moldovan",
    code: "ro",
  },
  {
    name: "Romansh",
    code: "rm",
  },
  {
    name: "Rundi",
    code: "rn",
  },
  {
    name: "Russian",
    code: "ru",
  },
  {
    name: "Northern Sami",
    code: "se",
  },
  {
    name: "Samoan",
    code: "sm",
  },
  {
    name: "Sango",
    code: "sg",
  },
  {
    name: "Sanskrit",
    code: "sa",
  },
  {
    name: "Sardinian",
    code: "sc",
  },
  {
    name: "Serbian",
    code: "sr",
  },
  {
    name: "Shona",
    code: "sn",
  },
  {
    name: "Sindhi",
    code: "sd",
  },
  {
    name: "Sinhala, Sinhalese",
    code: "si",
  },
  {
    name: "Slovak",
    code: "sk",
  },
  {
    name: "Slovenian",
    code: "sl",
  },
  {
    name: "Somali",
    code: "so",
  },
  {
    name: "Southern Sotho",
    code: "st",
  },
  {
    name: "Spanish, Castilian",
    code: "es",
  },
  {
    name: "Sundanese",
    code: "su",
  },
  {
    name: "Swahili",
    code: "sw",
  },
  {
    name: "Swati",
    code: "ss",
  },
  {
    name: "Swedish",
    code: "sv",
  },
  {
    name: "Tagalog",
    code: "tl",
  },
  {
    name: "Tahitian",
    code: "ty",
  },
  {
    name: "Tajik",
    code: "tg",
  },
  {
    name: "Tamil",
    code: "ta",
  },
  {
    name: "Tatar",
    code: "tt",
  },
  {
    name: "Telugu",
    code: "te",
  },
  {
    name: "Thai",
    code: "th",
  },
  {
    name: "Tibetan",
    code: "bo",
  },
  {
    name: "Tigrinya",
    code: "ti",
  },
  {
    name: "Tonga (Tonga Islands)",
    code: "to",
  },
  {
    name: "Tsonga",
    code: "ts",
  },
  {
    name: "Tswana",
    code: "tn",
  },
  {
    name: "Turkish",
    code: "tr",
  },
  {
    name: "Turkmen",
    code: "tk",
  },
  {
    name: "Twi",
    code: "tw",
  },
  {
    name: "Uighur, Uyghur",
    code: "ug",
  },
  {
    name: "Ukrainian",
    code: "uk",
  },
  {
    name: "Urdu",
    code: "ur",
  },
  {
    name: "Uzbek",
    code: "uz",
  },
  {
    name: "Venda",
    code: "ve",
  },
  {
    name: "Vietnamese",
    code: "vi",
  },
  {
    name: "Volapük",
    code: "vo",
  },
  {
    name: "Walloon",
    code: "wa",
  },
  {
    name: "Welsh",
    code: "cy",
  },
  {
    name: "Wolof",
    code: "wo",
  },
  {
    name: "Xhosa",
    code: "xh",
  },
  {
    name: "Yiddish",
    code: "yi",
  },
  {
    name: "Yoruba",
    code: "yo",
  },
  {
    name: "Zhuang, Chuang",
    code: "za",
  },
  {
    name: "Zulu",
    code: "zu",
  },
];

//ISO Race || Nationalities data
export const nationalitiesData = [
  "Afghan",
  "Albanian",
  "Algerian",
  "American",
  "Andorran",
  "Angolan",
  "Anguillan",
  "Argentine",
  "Armenian",
  "Australian",
  "Austrian",
  "Azerbaijani",
  "Bahamian",
  "Bahraini",
  "Bangladeshi",
  "Barbadian",
  "Belarusian",
  "Belgian",
  "Belizean",
  "Beninese",
  "Bermudian",
  "Bhutanese",
  "Bolivian",
  "Botswanan",
  "Brazilian",
  "British",
  "British Virgin Islander",
  "Bruneian",
  "Bulgarian",
  "Burkinan",
  "Burmese",
  "Burundian",
  "Cambodian",
  "Cameroonian",
  "Canadian",
  "Cape Verdean",
  "Cayman Islander",
  "Central African",
  "Chadian",
  "Chilean",
  "Chinese",
  "Citizen of Antigua and Barbuda",
  "Citizen of Bosnia and Herzegovina",
  "Citizen of Guinea-Bissau",
  "Citizen of Kiribati",
  "Citizen of Seychelles",
  "Citizen of the Dominican Republic",
  "Citizen of Vanuatu ",
  "Colombian",
  "Comoran",
  "Congolese (Congo)",
  "Congolese (DRC)",
  "Cook Islander",
  "Costa Rican",
  "Croatian",
  "Cuban",
  "Cymraes",
  "Cymro",
  "Cypriot",
  "Czech",
  "Danish",
  "Djiboutian",
  "Dominican",
  "Dutch",
  "East Timorese",
  "Ecuadorean",
  "Egyptian",
  "Emirati",
  "English",
  "Equatorial Guinean",
  "Eritrean",
  "Estonian",
  "Ethiopian",
  "Faroese",
  "Fijian",
  "Filipino",
  "Finnish",
  "French",
  "Gabonese",
  "Gambian",
  "Georgian",
  "German",
  "Ghanaian",
  "Gibraltarian",
  "Greek",
  "Greenlandic",
  "Grenadian",
  "Guamanian",
  "Guatemalan",
  "Guinean",
  "Guyanese",
  "Haitian",
  "Honduran",
  "Hong Konger",
  "Hungarian",
  "Icelandic",
  "Indian",
  "Indonesian",
  "Iranian",
  "Iraqi",
  "Irish",
  "Israeli",
  "Italian",
  "Ivorian",
  "Jamaican",
  "Japanese",
  "Jordanian",
  "Kazakh",
  "Kenyan",
  "Kittitian",
  "Kosovan",
  "Kuwaiti",
  "Kyrgyz",
  "Lao",
  "Latvian",
  "Lebanese",
  "Liberian",
  "Libyan",
  "Liechtenstein citizen",
  "Lithuanian",
  "Luxembourger",
  "Macanese",
  "Macedonian",
  "Malagasy",
  "Malawian",
  "Malaysian",
  "Maldivian",
  "Malian",
  "Maltese",
  "Marshallese",
  "Martiniquais",
  "Mauritanian",
  "Mauritian",
  "Mexican",
  "Micronesian",
  "Moldovan",
  "Monegasque",
  "Mongolian",
  "Montenegrin",
  "Montserratian",
  "Moroccan",
  "Mosotho",
  "Mozambican",
  "Namibian",
  "Nauruan",
  "Nepalese",
  "New Zealander",
  "Nicaraguan",
  "Nigerian",
  "Nigerien",
  "Niuean",
  "North Korean",
  "Northern Irish",
  "Norwegian",
  "Omani",
  "Pakistani",
  "Palauan",
  "Palestinian",
  "Panamanian",
  "Papua New Guinean",
  "Paraguayan",
  "Peruvian",
  "Pitcairn Islander",
  "Polish",
  "Portuguese",
  "Prydeinig",
  "Puerto Rican",
  "Qatari",
  "Romanian",
  "Russian",
  "Rwandan",
  "Salvadorean",
  "Sammarinese",
  "Samoan",
  "Sao Tomean",
  "Saudi Arabian",
  "Scottish",
  "Senegalese",
  "Serbian",
  "Sierra Leonean",
  "Singaporean",
  "Slovak",
  "Slovenian",
  "Solomon Islander",
  "Somali",
  "South African",
  "South Korean",
  "South Sudanese",
  "Spanish",
  "Sri Lankan",
  "St Helenian",
  "St Lucian",
  "Stateless",
  "Sudanese",
  "Surinamese",
  "Swazi",
  "Swedish",
  "Swiss",
  "Syrian",
  "Taiwanese",
  "Tajik",
  "Tanzanian",
  "Thai",
  "Togolese",
  "Tongan",
  "Trinidadian",
  "Tristanian",
  "Tunisian",
  "Turkish",
  "Turkmen",
  "Turks and Caicos Islander",
  "Tuvaluan",
  "Ugandan",
  "Ukrainian",
  "Uruguayan",
  "Uzbek",
  "Vatican citizen",
  "Venezuelan",
  "Vietnamese",
  "Vincentian",
  "Wallisian",
  "Welsh",
  "Yemeni",
  "Zambian",
  "Zimbabwean",
];

// Ethnicity || Countries Data
export const countriesData = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "American Samoa",
  "Andorra",
  "Angola",
  "Anguilla",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Aruba",
  "Australia",
  "Australian External Territories",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bermuda",
  "Bhutan",
  "Bolivia (Plurinational State of)",
  "Bonaire, Sint Eustatius and Saba",
  "Bosnia and Herzegovina",
  "Botswana",
  "Brazil",
  "British Virgin Islands",
  "Brunei Darussalam",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Cape Verde",
  "Cayman Islands",
  "Central African Rep.",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Comoros",
  "Congo",
  "Cook Islands",
  "Costa Rica",
  "Côte d'Ivoire",
  "Croatia",
  "Cuba",
  "Curaçao",
  "Cyprus",
  "Czech Rep.",
  "Dem. People's Rep. of Korea",
  "Dem. Rep. of the Congo",
  "Denmark",
  "Diego Garcia",
  "Djibouti",
  "Dominica",
  "Dominican Rep.",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Ethiopia",
  "Falkland Islands (Malvinas)",
  "Faroe Islands",
  "Fiji",
  "Finland",
  "France",
  "French Dep. and Territories in the Indian Ocean",
  "French Guiana",
  "French Polynesia",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Gibraltar",
  "Global Mobile Satellite System (GMSS), shared",
  "Greece",
  "Greenland",
  "Grenada",
  "Guadeloupe",
  "Guam",
  "Guatemala",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Honduras",
  "Hong Kong, China",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Inmarsat SNAC",
  "Iran (Islamic Republic of)",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Korea (Rep. of)",
  "Kuwait",
  "Kyrgyzstan",
  "Lao P.D.R.",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Macao, China",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Martinique",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Micronesia",
  "Moldova (Republic of)",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Montserrat",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Caledonia",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "Niue",
  "Northern Marianas",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Puerto Rico",
  "Qatar",
  "Romania",
  "Russian Federation",
  "Rwanda",
  "Saint Helena, Ascension and Tristan da Cunha",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Pierre and Miquelon",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Sint Maarten (Dutch part)",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Swaziland",
  "Sweden",
  "Switzerland",
  "Syrian Arab Republic",
  "Taiwan, China",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "The Former Yugoslav Republic of Macedonia",
  "Timor-Leste",
  "Togo",
  "Tokelau",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Turks and Caicos Islands",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "United States Virgin Islands",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Vatican",
  "Venezuela (Bolivarian Republic of)",
  "Viet Nam",
  "Wallis and Futuna",
  "Yemen",
  "Zambia",
  "Zimbabwe",
];


//Timezone Data
export const timezoneData = [
  { value: 'UTC', label: 'UTC (Coordinated Universal Time)' },
  { value: 'GMT', label: 'GMT (Greenwich Mean Time)' },
  { value: 'America/New_York', label: 'EST/EDT (Eastern Time - New York)' },
  { value: 'America/Chicago', label: 'CST/CDT (Central Time - Chicago)' },
  { value: 'America/Denver', label: 'MST/MDT (Mountain Time - Denver)' },
  { value: 'America/Los_Angeles', label: 'PST/PDT (Pacific Time - Los Angeles)' },
  { value: 'America/Anchorage', label: 'AKST/AKDT (Alaska Time - Anchorage)' },
  { value: 'Pacific/Honolulu', label: 'HST (Hawaii-Aleutian Time - Honolulu)' },
  { value: 'Europe/London', label: 'BST (British Summer Time - London)' },
  { value: 'Europe/Paris', label: 'CET/CEST (Central European Time - Paris, Berlin)' },
  { value: 'Europe/Helsinki', label: 'EET/EEST (Eastern European Time - Athens, Helsinki)' },
  { value: 'Asia/Kolkata', label: 'IST (India Standard Time - New Delhi)' },
  { value: 'Asia/Shanghai', label: 'CST (China Standard Time - Beijing)' },
  { value: 'Asia/Tokyo', label: 'JST (Japan Standard Time - Tokyo)' },
  { value: 'Australia/Sydney', label: 'AEST/AEDT (Australian Eastern Time - Sydney)' },
];

export const stateData = [
  {
    id: "1",
    name: "Alabama",
    timezone: "America/Chicago",
    abbreviation: "CST",
    standard_time: "Central",
  },
  {
    id: "2",
    name: "Alaska",
    timezone: "America/Anchorage",
    abbreviation: "AKST",
    standard_time: "Alaska",
  },
  {
    id: "3",
    name: "Arizona",
    timezone: "America/Phoenix",
    abbreviation: "MST",
    standard_time: "Mountain",
  },
  {
    id: "4",
    name: "Arkansas",
    timezone: "America/Chicago",
    abbreviation: "CST",
    standard_time: "Central",
  },
  {
    id: "5",
    name: "California",
    timezone: "America/Los_Angeles",
    abbreviation: "PST",
    standard_time: "Pacific",
  },
  {
    id: "6",
    name: "Colorado",
    timezone: "America/Denver",
    abbreviation: "MST",
    standard_time: "Mountain",
  },
  {
    id: "7",
    name: "Connecticut",
    timezone: "America/New_York",
    abbreviation: "EST",
    standard_time: "Eastern",
  },
  {
    id: "8",
    name: "Delaware",
    timezone: "America/New_York",
    abbreviation: "EST",
    standard_time: "Eastern",
  },
  {
    id: "9",
    name: "District of Columbia",
    timezone: "America/New_York",
    abbreviation: "EST",
    standard_time: "Eastern",
  },
  {
    id: "10",
    name: "Florida",
    timezone: "America/New_York",
    abbreviation: "EST",
    standard_time: "Eastern",
  },
  {
    id: "11",
    name: "Georgia",
    timezone: "America/New_York",
    abbreviation: "EST",
    standard_time: "Eastern",
  },
  {
    id: "12",
    name: "Guam",
    timezone: "America/Guam ",
    abbreviation: "ChST",
    standard_time: "Chamorro",
  },
  {
    id: "13",
    name: "Hawaii",
    timezone: "Pacific/Honolulu",
    abbreviation: "HST",
    standard_time: "Hawaii",
  },
  {
    id: "14",
    name: "Idaho",
    timezone: "America/Boise",
    abbreviation: "MST",
    standard_time: "Mountain",
  },
  {
    id: "15",
    name: "Illinois",
    timezone: "America/Chicago",
    abbreviation: "CST",
    standard_time: "Central",
  },
  {
    id: "16",
    name: "Indiana",
    timezone: "America/Indiana/Indianapolis",
    abbreviation: "EST",
    standard_time: "Eastern",
  },
  {
    id: "17",
    name: "Iowa",
    timezone: "America/Chicago",
    abbreviation: "CST",
    standard_time: "Central",
  },
  {
    id: "18",
    name: "Kansas",
    timezone: "America/Chicago",
    abbreviation: "CST",
    standard_time: "Central",
  },
  {
    id: "19",
    name: "Kentucky",
    timezone: "America/New_York",
    abbreviation: "EST",
    standard_time: "Eastern",
  },
  {
    id: "20",
    name: "Louisiana",
    timezone: "America/Chicago",
    abbreviation: "CST",
    standard_time: "Central",
  },
  {
    id: "21",
    name: "Maine",
    timezone: "America/New_York",
    abbreviation: "EST",
    standard_time: "Eastern",
  },
  {
    id: "22",
    name: "Maryland",
    timezone: "America/New_York",
    abbreviation: "EST",
    standard_time: "Eastern",
  },
  {
    id: "23",
    name: "Massachusetts",
    timezone: "America/New_York",
    abbreviation: "EST",
    standard_time: "Eastern",
  },
  {
    id: "24",
    name: "Michigan",
    timezone: "America/Detroit",
    abbreviation: "EST",
    standard_time: "Eastern",
  },
  {
    id: "25",
    name: "Minnesota",
    timezone: "America/Chicago",
    abbreviation: "CST",
    standard_time: "Central",
  },
  {
    id: "26",
    name: "Mississippi",
    timezone: "America/Chicago",
    abbreviation: "CST",
    standard_time: "Central",
  },
  {
    id: "27",
    name: "Missouri",
    timezone: "America/Chicago",
    abbreviation: "CST",
    standard_time: "Central",
  },
  {
    id: "28",
    name: "Montana",
    timezone: "America/Denver",
    abbreviation: "MST",
    standard_time: "Mountain",
  },
  {
    id: "29",
    name: "Nebraska",
    timezone: "America/Chicago",
    abbreviation: "CST",
    standard_time: "Central",
  },
  {
    id: "30",
    name: "Nevada",
    timezone: "America/Los_Angeles",
    abbreviation: "PST",
    standard_time: "Pacific",
  },
  {
    id: "31",
    name: "New Hampshire",
    timezone: "America/New_York",
    abbreviation: "EST",
    standard_time: "Eastern",
  },
  {
    id: "32",
    name: "New Jersey",
    timezone: "America/New_York",
    abbreviation: "EST",
    standard_time: "Eastern",
  },
  {
    id: "33",
    name: "New Mexico",
    timezone: "America/Denver",
    abbreviation: "MST",
    standard_time: "Mountain",
  },
  {
    id: "34",
    name: "New York",
    timezone: "America/New_York",
    abbreviation: "EST",
    standard_time: "Eastern",
  },
  {
    id: "35",
    name: "North Carolina",
    timezone: "America/New_York",
    abbreviation: "EST",
    standard_time: "Eastern",
  },
  {
    id: "36",
    name: "North Dakota",
    timezone: "America/Chicago",
    abbreviation: "CST",
    standard_time: "Central",
  },
  {
    id: "37",
    name: "Ohio",
    timezone: "America/New_York",
    abbreviation: "EST",
    standard_time: "Eastern",
  },
  {
    id: "38",
    name: "Oklahoma",
    timezone: "America/Chicago",
    abbreviation: "CST",
    standard_time: "Central",
  },
  {
    id: "39",
    name: "Oregon",
    timezone: "America/Los_Angeles",
    abbreviation: "PST",
    standard_time: "Pacific",
  },
  {
    id: "40",
    name: "Pennsylvania",
    timezone: "America/New_York",
    abbreviation: "EST",
    standard_time: "Eastern",
  },
  {
    id: "41",
    name: "Rhode Island",
    timezone: "America/New_York",
    abbreviation: "EST",
    standard_time: "Eastern",
  },
  {
    id: "42",
    name: "South Carolina",
    timezone: "America/New_York",
    abbreviation: "EST",
    standard_time: "Eastern",
  },
  {
    id: "43",
    name: "South Dakota",
    timezone: "America/Chicago",
    abbreviation: "CST",
    standard_time: "Central",
  },
  {
    id: "44",
    name: "Tennessee",
    timezone: "America/Chicago",
    abbreviation: "CST",
    standard_time: "Central",
  },
  {
    id: "45",
    name: "Texas",
    timezone: "America/Chicago",
    abbreviation: "CST",
    standard_time: "Central",
  },
  {
    id: "46",
    name: "Utah",
    timezone: "America/Denver",
    abbreviation: "MST",
    standard_time: "Mountain",
  },
  {
    id: "47",
    name: "Vermont",
    timezone: "America/New_York",
    abbreviation: "EST",
    standard_time: "Eastern",
  },
  {
    id: "48",
    name: "Virginia",
    timezone: "America/New_York",
    abbreviation: "EST",
    standard_time: "Eastern",
  },
  {
    id: "49",
    name: "Washington",
    timezone: "America/Los_Angeles",
    abbreviation: "PST",
    standard_time: "Pacific",
  },
  {
    id: "50",
    name: "West Virginia",
    timezone: "America/New_York",
    abbreviation: "EST",
    standard_time: "Eastern",
  },
  {
    id: "51",
    name: "Wisconsin",
    timezone: "America/Chicago",
    abbreviation: "CST",
    standard_time: "Central",
  },
  {
    id: "52",
    name: "Wyoming",
    timezone: "America/Denver",
    abbreviation: "MST",
    standard_time: "Mountain",
  },
];